# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true; # 开机自动给适配器通电
  # 2. 开启音频服务（PipeWire 是现在的王道，对蓝牙耳机兼容性最好）
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
    # 关键：开启 PipeWire 的蓝牙支持
    wireplumber.enable = true; # 负责管理蓝牙连接逻辑的“大脑”
    wireplumber.extraConfig."10-bluez" = {
      "monitor.bluez5.properties" = {
        "bluez5.enable-sbc-xq" = true;
        "bluez5.enable-msbc" = true;
        "bluez5.enable-hw-volume" = true;
      };
    };
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = true;
  hardware.graphics = {
    enable = true;
    enable32Bit = true; # 建议开启，增加兼容性
  };
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "amd_iommu=off"
  ];
  # 根目录挂载 @ 子卷
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/69fb64e8-926b-41bd-98da-025e32ab1d20";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
      "discard=async"
    ];
  };

  # 用户目录挂载 @home 子卷
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/69fb64e8-926b-41bd-98da-025e32ab1d20";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "discard=async"
    ];
  };

  # Nix Store 挂载 @nix 子卷 (NixOS 的灵魂所在)
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/69fb64e8-926b-41bd-98da-025e32ab1d20";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
      "discard=async"
    ];
  };

  # 日志目录挂载 @log 子卷
  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/69fb64e8-926b-41bd-98da-025e32ab1d20";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "compress=zstd"
      "noatime"
      "discard=async"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/23BB-F42B";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];
  # 笔记本开启充电保护
  systemd.tmpfiles.rules = [
    "f /var/lib/upower/charging-threshold-status 0644 root root - 1"
  ];
}
