# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # boot.loader.efi.efiSysMountPoint = "/boot/ESP";

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # 根目录挂载 @ 子卷
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a1a84a5b-67d7-4695-8ad7-9a934114adc8";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
      "discard=async"
    ];
  };

  # 用户目录挂载 @home 子卷
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a1a84a5b-67d7-4695-8ad7-9a934114adc8";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "discard=async"
    ];
  };

  # Nix Store 挂载 @nix 子卷 (NixOS 的灵魂所在)
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a1a84a5b-67d7-4695-8ad7-9a934114adc8";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
      "discard=async"
    ];
  };

  # 日志目录挂载 @log 子卷
  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/a1a84a5b-67d7-4695-8ad7-9a934114adc8";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "compress=zstd"
      "noatime"
      "discard=async"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/23BB-F42B";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
