Net/ThemeName "Flat-Remix-GTK-Violet-Light-Solid"
Net/IconThemeName "Tokyonight-Moon"
Gtk/CursorThemeName "Bibata-Modern-Ice"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
