
[general]
live_config_reload = true
import = [
  "theme.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
option_as_alt = "Both"
resize_increments = true
startup_mode = "Windowed"
title = "Alacritty"

[window.identity]
class = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0

[cursor]
blink_interval = 500

[cursor.style]
shape = "Block"
blinking = "Always"

[font]
size = 11
builtin_box_drawing = true

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

[font.bold]
family = "ComicShannsMono Nerd Font"
style = "Bold"

[font.italic]
family = "ComicShannsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "ComicShannsMono Nerd Font"
style = "Bold Italic"

[scrolling]
history = 0
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ""

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[colors]
draw_bold_text_with_bright_colors = false
