name: alpine-docker
on:
  push:
    branches:
      - main
    paths:
      - "rootfs.Dockerfile"
      - "alpine/docker/**"
  schedule:
    - cron: "0 0 1 * *"
env:
  TZ: Asia/Shanghai
jobs:
  build:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          # registry.cn-hangzhou.aliyuncs.com
          # ccr.ccs.tencentyun.com
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Generate Tag List
        run: |
          sed -i -e 's|${IMAGE}|alpine|' ./rootfs.Dockerfile
          docker system prune -af
          echo "TAGS<<EOF" >> $GITHUB_ENV
          echo ${{ secrets.REGISTRY }}/yxing-xyz/linux:alpine >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          file: "./rootfs.Dockerfile"
          tags: ${{ env.TAGS }}
          context: ./alpine/docker
