name: arch-docker
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/arch.yaml"
      - "arch/docker/rootfs.Dockerfile"
      - "arch/docker/rootfs.sh"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch: # 添加这一行以支持手动触发
      inputs: # 可选：定义输入参数
        exampleInput:
          description: '示例输入参数'
          required: false
          default: 'default_value'
env:
  TZ: Asia/Shanghai
jobs:
  build:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          # registry.cn-hangzhou.aliyuncs.com
          # ccr.ccs.tencentyun.com
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Generate Tag List
        run: |
          docker system prune -af
          echo "TAGS<<EOF" >> $GITHUB_ENV
          echo  ${{ secrets.REGISTRY }}/${{ secrets.USERNAME }}/linux:arch >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          file: ./arch/docker/rootfs.Dockerfile
          context: ./arch/docker
          tags: ${{ env.TAGS }}
      # - name: Setup Debug Session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   timeout-minutes: 600
      #   with:
      #     detached: true
